# .github/workflows/build-coreml-model.yml

name: Build On-Device Core ML Model

on:
  workflow_dispatch:

jobs:
  build-coreml:
    runs-on: macos-14
    
    # Define the model ID here for easy configuration
    env:
      MODEL_ID: "microsoft/Phi-3-mini-4k-instruct"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache Pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/scripts/requirements.txt') }} # Or just a static key if no requirements file
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch transformers coremltools sentencepiece

      - name: Create model output directory
        run: mkdir -p Models

      - name: Convert Hugging Face model to Core ML
        # The script will now use the MODEL_ID defined in the 'env' block above
        run: python scripts/convert_model_to_coreml.py --quantization float16

      - name: Compile Core ML model for iOS
        run: xcrun coremlc compile Models/LLM.mlmodel Models/

      - name: Upload Core ML model and tokenizer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: on-device-models
          path: |
            Models/LLM.mlmodelc
            Models/tokenizer.model
          retention-days: 7 # Keep artifacts for a week