name: Build Native Modules & TurboModules

on:
  push:
    branches: [main, develop]
    paths:
      - 'ios/**'
      - 'android/**'
      - 'specs/**'
      - 'scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'ios/**'
      - 'android/**'
      - 'specs/**'
      - 'scripts/**'

env:
  XCODE_VERSION: '15.2'
  NODE_VERSION: '20'
  REACT_NATIVE_VERSION: '0.76.7'

jobs:
  # Validate TurboModule Specifications
  validate-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install -g @react-native-community/cli
          npm install

      - name: Validate TypeScript Specs
        run: |
          npx tsc --noEmit specs/NativePhi4LLM.ts
          npx tsc --noEmit specs/NativeMathTools.ts
          echo "✅ TurboModule specs validation passed"

      - name: Generate Native Code
        run: |
          npx react-native codegen --platform ios --outputPath ios/generated
          npx react-native codegen --platform android --outputPath android/generated
          echo "✅ Native code generation completed"

  # Build iOS Native Modules
  build-ios:
    runs-on: macos-latest
    needs: validate-specs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm install
          cd ios && pod install --repo-update

      - name: Setup Ruby for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ios

      - name: Install CocoaPods Dependencies
        run: |
          cd ios
          bundle exec pod install --clean-install

      - name: Build iOS Native Modules
        run: |
          cd ios
          xcodebuild -workspace AdvancedAgentApp.xcworkspace \
                     -scheme AdvancedAgentApp \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
                     -quiet \
                     build
          echo "✅ iOS native modules built successfully"

      - name: Test Native Phi-4 Module
        run: |
          cd ios
          xcodebuild -workspace AdvancedAgentApp.xcworkspace \
                     -scheme AdvancedAgentApp \
                     -configuration Debug \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2' \
                     -quiet \
                     test
          echo "✅ Native module tests passed"

      - name: Archive iOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-native-modules
          path: |
            ios/build/
            ios/Pods/
          retention-days: 7

  # Build Android Native Modules
  build-android:
    runs-on: ubuntu-latest
    needs: validate-specs
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Android Native Modules
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon --stacktrace
          echo "✅ Android native modules built successfully"

      - name: Test Android Native Modules
        run: |
          cd android
          ./gradlew testDebugUnitTest --no-daemon
          echo "✅ Android native module tests passed"

      - name: Archive Android Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-native-modules
          path: |
            android/app/build/
            android/build/
          retention-days: 7

  # Validate TurboModule Integration
  test-turbomodules:
    runs-on: macos-latest
    needs: [build-ios, build-android]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Download iOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ios-native-modules
          path: ios/

      - name: Test TurboModule Integration
        run: |
          # Test TurboModule specs compilation
          npm run test:turbomodules
          
          # Validate native bridge functionality
          npm run test:native-bridge
          
          echo "✅ TurboModule integration tests passed"

      - name: Generate TurboModule Documentation
        run: |
          npx typedoc specs/ --out docs/turbomodules/
          echo "✅ TurboModule documentation generated"

      - name: Archive Documentation
        uses: actions/upload-artifact@v4
        with:
          name: turbomodule-docs
          path: docs/turbomodules/
          retention-days: 30