# .github/workflows/compile-native.yml

name: DEBUG - Compile Native iOS Project

on:
  workflow_dispatch: # Manual trigger only
  push:
    branches: [ "main" ]

jobs:
  debug-paths:
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 1. List files at the initial working directory
        run: |
          echo "--- Files and directories at initial location (pwd) ---"
          pwd
          echo "--------------------------------------------------------"
          ls -laR
          echo "--------------------------------------------------------"

      - name: 2. List files one directory up
        run: |
          echo "--- Files and directories one level UP (../) ---"
          pwd
          cd ..
          echo "New PWD: $(pwd)"
          echo "------------------------------------------------"
          ls -laR
          echo "------------------------------------------------"