# .github/workflows/compile-native.yml

name: Compile Native iOS Project (Turbo Modules)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'ios/**'
      - 'modules/**'
      - 'package.json'
      - 'app.json'
      - 'patches/**'

jobs:
  compile-ios:
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies & Apply Patches
        # This now assumes a lockfile will be created or restored by the cache
        run: |
          npx patch-package
          npm ci

      - name: Generate native iOS project
        run: npx expo prebuild --platform ios --no-install --clean

      - name: Modify Podfile to add Third-Party Sources
        run: |
          PODFILE_PATH="ios/Podfile"
          {
            echo "source 'https://github.com/google/sentencepiece.git'"
            echo "source 'https://github.com/CocoaPods/Specs.git'"
            cat "$PODFILE_PATH"
          } > "$PODFILE_PATH.tmp" && mv "$PODFILE_PATH.tmp" "$PODFILE_PATH"
          echo "--- Modified Podfile for SentencePiece ---"
          cat "$PODFILE_PATH"

      # *** CORRECTED RUBY/PODS SECTION ***
      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          # Tell bundler to look for the Gemfile inside the ios directory
          working-directory: ./ios 
          bundler-cache: true # This will run 'bundle install' for us

      - name: Run Pod Install
        # This step now only needs to run pod install
        working-directory: ./ios
        run: pod install --repo-update
      
      - name: Verify Pod Installation
        run: |
          if [ ! -d "ios/Pods/SentencePiece" ]; then
            echo "::error::'pod install' failed. SentencePiece pod was not found."
            exit 1
          fi
          echo "✅ Pods installed successfully."

      - name: Compile Xcode Project
        run: |
          xcodebuild build -workspace ios/nativemongars.xcworkspace \
            -scheme nativemongars \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro'