# .github/workflows/compile-native.yml

name: Compile Native iOS Project (Turbo Modules)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'native-monGARS/**'
      - 'modules/**'
      - 'patches/**'

jobs:
  compile-ios:
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      # Cache is defined relative to the repo root
      - name: Cache npm dependencies
        id: npm-cache
        uses: actions/cache@v4
        with:
          path: native-monGARS/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('native-monGARS/package-lock.json') }}

      - name: Install Dependencies & Apply Patches
        # Run all commands from within the project directory
        working-directory: ./native-monGARS
        run: |
          npx patch-package
          npm ci

      - name: Verify Critical Dependencies
        working-directory: ./native-monGARS
        run: |
          if [ ! -f "node_modules/react-native/package.json" ]; then
            echo "::error::'react-native' package was not found. 'npm ci' failed."
            exit 1
          fi
          echo "✅ Critical dependencies are present."

      - name: Generate native iOS project
        working-directory: ./native-monGARS
        run: npx expo prebuild --platform ios --no-install --clean

      - name: Modify Podfile to add SentencePiece source
        working-directory: ./native-monGARS
        run: |
          PODFILE_PATH="ios/Podfile"
          {
            echo "source 'https://github.com/google/sentencepiece.git'"
            echo "source 'https://github.com/CocoaPods/Specs.git'"
            cat "$PODFILE_PATH"
          } > "$PODFILE_PATH.tmp" && mv "$PODFILE_PATH.tmp" "$PODFILE_PATH"
          echo "--- Modified Podfile ---"
          cat "$PODFILE_PATH"
          echo "------------------------"

      - name: Set up Ruby and Bundler for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          # working-directory for setup-ruby needs to be relative to the repo root
          working-directory: native-monGARS/ios

      - name: Install CocoaPods
        working-directory: ./native-monGARS/ios
        run: bundle install

      - name: Run Pod Install
        working-directory: ./native-monGARS/ios
        run: pod install --repo-update
      
      - name: Verify Pod Installation
        working-directory: ./native-monGARS
        run: |
          if [ ! -d "ios/Pods/SentencePiece" ]; then
            echo "::error::'pod install' failed. SentencePiece pod was not found."
            exit 1
          fi
          echo "✅ Pods installed successfully."

      - name: Compile Xcode Project
        working-directory: ./native-monGARS
        run: |
          xcodebuild build -workspace ios/nativemongars.xcworkspace \
            -scheme nativemongars \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro'