# .github/workflows/compile-native.yml

name: Compile Native iOS Project (Turbo Modules)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'ios/**'
      - 'modules/**'
      - 'package.json'
      - 'app.json'
      - 'patches/**'

jobs:
  compile-ios:
    runs-on: macos-14
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          # Caching now uses the correct root-level lockfile path
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install Dependencies & Apply Patches
        run: |
          # These commands run from the repository root
          npx patch-package
          npm ci

      - name: Generate native iOS project
        run: npx expo prebuild --platform ios --no-install --clean

      - name: Modify Podfile to add Third-Party Sources
        run: |
          PODFILE_PATH="ios/Podfile"
          # This robust method prepends the required source lines to the Podfile
          {
            echo "source 'https://github.com/google/sentencepiece.git'"
            echo "source 'https://github.com/CocoaPods/Specs.git'"
            cat "$PODFILE_PATH"
          } > "$PODFILE_PATH.tmp" && mv "$PODFILE_PATH.tmp" "$PODFILE_PATH"
          echo "--- Modified Podfile for SentencePiece ---"
          cat "$PODFILE_PATH"

      - name: Set up Ruby and Bundler for CocoaPods
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          # This action requires the path to the directory with the Gemfile
          working-directory: ./ios

      - name: Install and Run Pod Install
        # These commands need to be run from the ios directory
        working-directory: ./ios
        run: |
          bundle install
          pod install --repo-update
      
      - name: Verify Pod Installation
        run: |
          if [ ! -d "ios/Pods/SentencePiece" ]; then
            echo "::error::'pod install' failed. SentencePiece pod was not found."
            exit 1
          fi
          echo "✅ Pods installed successfully."

      - name: Compile Xcode Project
        run: |
          # The workspace and scheme paths are relative to the repository root
          xcodebuild build -workspace ios/nativemongars.xcworkspace \
            -scheme nativemongars \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro'