# .github/workflows/deploy-ios.yml

name: Deploy iOS to TestFlight

# CORRECTED TRIGGER:
# This workflow will now ONLY run when you manually trigger it from the
# GitHub Actions UI. This prevents accidental deployments on every push.
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'App Version (e.g., 1.0.1)'
        required: true
        type: string
      buildNumber:
        description: 'iOS Build Number (e.g., 3)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set up EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Download On-Device Model Artifact
        # This requires the "Build On-Device Core ML Model" workflow to have run successfully before.
        uses: actions/download-artifact@v4
        with:
          name: on-device-models
          path: ios/native-monGARS/Models
      
      - name: Verify Model Artifacts
        run: |
          echo "Verifying downloaded model artifacts..."
          ls -lR ios/native-monGARS/Models
          if [ ! -d "ios/native-monGARS/Models/LLM.mlmodelc" ]; then
            echo "::error::LLM.mlmodelc not found! Ensure the 'Build On-Device Core ML Model' workflow has run successfully."
            exit 1
          fi

      - name: Set App Version and Build Number
        run: |
          echo "Setting app version to ${{ github.event.inputs.version }} and build number to ${{ github.event.inputs.buildNumber }}"
          sudo apt-get update && sudo apt-get install -y jq
          jq '.expo.version = "${{ github.event.inputs.version }}" | .expo.ios.buildNumber = "${{ github.event.inputs.buildNumber }}"' app.json > tmp.$$.json && mv tmp.$$.json app.json
          echo "Updated app.json:"
          cat app.json

      - name: Build and Submit to TestFlight
        run: eas build --platform ios --profile release --non-interactive --auto-submit